title: Python Conference Deadlines # (Maintained by @jesperdramsch)
description: Countdowns to your favourite Python conferences
author: Jesper Dramsch

domain: "pythondeadlin.es"
baseurl: "/"

twitter_username: jesperdramsch
twitter_hashtag: python
github_username: jesperdramsch
github_repo: python-deadlines

markdown: kramdown
ga_id: G-X95YZPWV05

include: ['_pages']