title: Python Conference Deadlines # (Maintained by @jesperdramsch)
description: Countdowns to your favourite Python conferences
author: Jesper Dramsch

url: "https://pythondeadlin.es"
domain: "pythondeadlin.es"
baseurl: "/"

twitter_username: jesperdramsch
twitter_hashtag: python
github_username: jesperdramsch
github_repo: python-deadlines

markdown: kramdown
ga_id: G-X95YZPWV05
adsense_id: ca-pub-2158291969836277

include: ['_pages']

collections:
  posts:
    output: true
    permalink: /resources/:title/index:output_ext

plugins:
  - jekyll-sitemap