---
title: Python Conference Deadlines # (Maintained by @jesperdramsch)
description: Countdowns to your favourite Python conferences with calls for participation and resources to submit awesome talks!
tagline: Countdowns to your favourite Python conferences

url: 'https://pythondeadlin.es'
domain: 'pythondeadlin.es'
baseurl: ''

twitter_hashtag: python
github_username: jesperdramsch
github_repo: python-deadlines

markdown: kramdown
ga_id:
adsense_id:

include: ['_pages']

defaults:
- scope:
    path: ""
  values:
    seo_description_max_words: 200
    image: /static/img/python-deadlines-social-preview.png
    author: Jesper Dramsch
- scope:
    path: "_year"
  values:
    layout: "year"

collections:
  posts:
    output: true
    permalink: /resources/:title/index:output_ext
  years:
    output: true
    permalink: /archive/:title/index:output_ext

plugins:
- jekyll-include-cache
- jekyll-seo-tag
- jekyll-datapage-generator
- jekyll-maps
- jekyll-multiple-languages-plugin
- jekyll-sitemap

author:
  name: Jesper Dramsch
  url: https://dramsch.net


social:
  name: Jesper Dramsch
  links:
  - https://www.dramsch.net/linkedin
  - https://www.dramsch.net/mastodon
  - https://www.dramsch.net/threads
  - https://www.dramsch.net/github
  - https://www.dramsch.net/youtube

languages:
- en
- es
- de

exclude_from_localizations:
- 'static'

twitter:
  card: summary

maps:
  google:
    api_key: AIzaSyCEJ_S3OFxqrOfgx5WdSEMl8hxzgTFEw20

page_gen-dirs: true

page_gen:
- data: 'conferences'
  template: 'summary'
  dir: 'series'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')
  title_expr: record['conference']+" "+"Conference Series Overview"
- data: 'archive'
  template: 'summary'
  dir: 'series'
  name_expr: record['conference'].downcase.gsub(/[^\p{L}]+/, ' ').strip.gsub(' ', '-')
  title_expr: record['conference']+" "+"Conference Series Overview"
  filter_condition: site.pages.none? { |page| page.relative_path.include?(record['conference'].downcase.gsub(/[^\p{L}]+/, ' ').strip.gsub(' ', '-'))}
- data: 'legacy'
  template: 'summary'
  dir: 'series'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')
  title_expr: record['conference']+" "+"Conference Series Overview"
  filter_condition: site.pages.none? { |page| page.relative_path.include?(record['conference'].downcase.gsub(/[^\p{L}]+/, ' ').strip.gsub(' ', '-'))}
- data: 'conferences'
  template: 'conference'
  dir: 'conference'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')+"-"+record['year'].to_s
  title_expr: record['conference']+" "+record['year'].to_s+" Conference Deadlines"
- data: 'archive'
  template: 'conference'
  dir: 'conference'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')+"-"+record['year'].to_s
  title_expr: record['conference']+" "+record['year'].to_s+" Conference Deadlines"
- data: 'legacy'
  template: 'conference'
  dir: 'conference'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')+"-"+record['year'].to_s
  title_expr: record['conference']+" "+record['year'].to_s+" Conference Deadlines"
