title: Python Conference Deadlines # (Maintained by @jesperdramsch)
email: jesper@dramsch.net
description: Countdowns to your favourite Python conferences
author: Jesper Dramsch

domain: "pythondeadlin.es"
baseurl: ""

twitter_username: jesperdramsch
twitter_hashtag: python
github_username: jesperdramsch
github_repo: python-deadlines

markdown: kramdown
ga_id: UA-36274081-2
