title: Python Conference Deadlines # (Maintained by @jesperdramsch)
description: Countdowns to your favourite Python conferences
author: Jesper Dramsch

domain: "pythondeadlin.es"
baseurl: "/"

twitter_username: jesperdramsch
twitter_hashtag: python
github_username: jesperdramsch
github_repo: python-deadlines

markdown: kramdown
ga_id: G-X95YZPWV05
adsense_id: ca-pub-2158291969836277

include: ['_pages']

maps:
  google:
    api_key: AIzaSyAOfYptNDgCJNDNOe9i9F0RrxbKzXAJ2OY

jekyll_geocode:
  file-name: conferences.yml
  file-path: _data
  name: title
  address: place
  outputfile: places.yml

gems:
  - jekyll-geocode
  - jekyll-maps

exclude:
    - _data/places.yml # Maybe stop watching this file