title: Python Conference Deadlines # (Maintained by @jesperdramsch)
description: Countdowns to your favourite Python conferences with calls for participation and resources to submit awesome talks!
tagline: Countdowns to your favourite Python conferences

url: "https://pythondeadlin.es"
domain: "pythondeadlin.es"

twitter_username: jesperdramsch
twitter_hashtag: python
github_username: jesperdramsch
github_repo: python-deadlines

markdown: kramdown
ga_id: 
adsense_id: ca-pub-2158291969836277

include: ['_pages']

collections:
  posts:
    output: true
    permalink: /resources/:title/index:output_ext

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-datapage-generator
  - jekyll-maps

author:
  name: Jesper Dramsch
  url: https://dramsch.net
  twitter: jesperdramsch

social:
  name: Jesper Dramsch
  links:
    - https://twitter.com/JesperDramsch
    - https://www.dramsch.net/linkedin
    - https://www.dramsch.net/mastodon
    - https://www.dramsch.net/github

twitter:
  username: jesperdramsch
  card: summary

maps:
  google:
    api_key: AIzaSyCEJ_S3OFxqrOfgx5WdSEMl8hxzgTFEw20

page_gen-dirs: true

page_gen:
- data: 'conferences'
  template: 'conference'
  dir: 'conference'
  name_expr: record['title'].downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')+"-"+record['year'].to_s
  title_expr: record['title']+" "+record['year'].to_s+" Conference Deadlines – PythonDeadlin.es"
- data: 'archive'
  template: 'conference'
  dir: 'conference'
  name_expr: record['title'].downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')+"-"+record['year'].to_s
  title_expr: record['title']+" "+record['year'].to_s+" Conference Deadlines – PythonDeadlin.es"