---
title: Python Conference Deadlines # (Maintained by @jesperdramsch)
description: Countdowns to your favourite Python conferences with calls for participation and resources to submit awesome talks!
tagline: Countdowns to your favourite Python conferences

url: 'https://pythondeadlin.es'
domain: 'pythondeadlin.es'
baseurl: ''

twitter_username: jesperdramsch
twitter_hashtag: python
github_username: jesperdramsch
github_repo: python-deadlines

markdown: kramdown
ga_id:
adsense_id:

include: ['_pages']

collections:
  posts:
    output: true
    permalink: /resources/:title/index:output_ext
  years:
    output: true

plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-datapage-generator
- jekyll-maps
- jekyll-multiple-languages-plugin

author:
  name: Jesper Dramsch
  url: https://dramsch.net
  twitter: jesperdramsch


social:
  name: Jesper Dramsch
  links:
  - https://www.dramsch.net/linkedin
  - https://www.dramsch.net/mastodon
  - https://www.dramsch.net/threads
  - https://www.dramsch.net/github

languages:
- en
- es
- de

exclude_from_localizations:
- 'static'

twitter:
  username: jesperdramsch
  card: summary

maps:
  google:
    api_key: AIzaSyCEJ_S3OFxqrOfgx5WdSEMl8hxzgTFEw20

page_gen-dirs: true

page_gen:
- data: 'conferences'
  template: 'conference'
  dir: 'conference'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')+"-"+record['year'].to_s
  title_expr: record['conference']+" "+record['year'].to_s+" Conference Deadlines"
- data: 'archive'
  template: 'conference'
  dir: 'conference'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')+"-"+record['year'].to_s
  title_expr: record['conference']+" "+record['year'].to_s+" Conference Deadlines"
- data: 'legacy'
  template: 'conference'
  dir: 'conference'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')+"-"+record['year'].to_s
  title_expr: record['conference']+" "+record['year'].to_s+" Conference Deadlines"
- data: 'legacy'
  template: 'summary'
  dir: 'series'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')
  title_expr: record['conference']+" "+"Conference Summary"
- data: 'archive'
  template: 'summary'
  dir: 'series'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')
  title_expr: record['conference']+" "+"Conference Summary"
- data: 'conferences'
  template: 'summary'
  dir: 'series'
  name_expr: record['conference'].downcase.strip.gsub(' ', '-').gsub(/[^\p{L}]+/, '-')
  title_expr: record['conference']+" "+"Conference Summary"
